version: '2'
services:
  uk:
    image: users
    container_name: "uk"
    ports:
      - "4000:4000"
    depends_on:
      - dbuk
  dbuk:
    image: dbu
    container_name: "dbuk"
    ports:
      - "172.17.0.1:3306:3306"
    volumes:
      - /var/lib/mysql/a2:/var/lib/mysql
    depends_on:
      - registrator

  senderk:
    image: sender
    container_name: "senderk"
    ports:
      - "3800:3800"
    depends_on:
      - dbsk
  dbsk:
    image: dbs
    container_name: "dbsk"
    ports:
      - "172.17.0.1:3308:3308"
    volumes:
      - /var/lib/mysql/a4:/var/lib/mysql
    depends_on:
      - registrator

  authk:
    image: auth
    container_name: "authk"
    ports:
      - "3900:3900"
    depends_on:
      - dbak
  dbak:
    image: dba
    container_name: "dbak"
    ports:
      - "172.17.0.1:3307:3307"
    volumes:
      - /var/lib/mysql/a3:/var/lib/mysql
    depends_on:
      - registrator

  emailk:
    image: email
    container_name: "emailk"
    ports:
      - "3600:3600"
    depends_on:
      - registrator

  smsk:
    image: sms
    container_name: "smsk"
    ports:
      - "3700:3700"
    depends_on:
      - registrator

  apik:
    image: api
    container_name: "apik"
    ports:
      - "3550:3550"
    depends_on:
      - registrator

  clientk:
    image: client
    container_name: "clientk"
    ports:
      - "3500:3500"
    depends_on:
      - registrator

  consul:
    image: progrium/consul
    container_name: "consul"
    volumes:
        - /mnt:/data
    ports:
        - "$HOST_IP:8300:8300"
        - "$HOST_IP:8301:8301"
        - "$HOST_IP:8301:8301/udp"
        - "$HOST_IP:8302:8302"
        - "$HOST_IP:8302:8302/udp"
        - "$HOST_IP:8400:8400"
        - "$HOST_IP:8500:8500"
        - "$DOCKER_BRIDGE_IP:53:53/udp"
    command: "-server -advertise $HOST_IP -bootstrap -node=master"

#    -h ilya-Lenovo-V580c     $HOSTNAME
  registrator:
    image: gliderlabs/registrator:latest
    container_name: "registrator"
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock
    command: "consul://$HOST_IP:8500 "
    depends_on:
      - consul