export const REG_CLIENT_REQUEST = 'REG_CLIENT_REQUEST';
export const REG_CLIENT_SUCCESS = 'REG_CLIENT_SUCCESS';
export const REG_CLIENT_FAILURE = 'REG_CLIENT_FAILURE';
export const CHECK_TYPE_OF_OWNERSHIP = 'CHECK_TYPE_OF_OWNERSHIP';
export const REG_OVER = 'REG_OVER';
export const ENTER_ADDRESS = 'ENTER_ADDRESS';
