export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const READ_CLIENT_SUCCESS = 'READ_CLIENT_SUCCESS';
export const REST_SCAN_SUCCESS = 'REST_SCAN_SUCCESS';
export const STATMENT_SUCCESS = 'STATMENT_SUCCESS';
export const SELECT_CHANGE = 'SELECT_CHANGE';
export const CERTIFICATE_APPLICATION = 'CERTIFICATE_APPLICATION';
export const STATES_STATEMENT = 'STATES_STATEMENT';










